### ISSUE TITLE
I'm having difficulties trying to send raw command to move tabs

### ISSUE THREAD

**Issue by jackmac79** [smblott-github/chromix#11]
using chromix raw chrome.tabs.move I don't know how to format the arguments to be passed on correctly
(tID and wID are the actual window/tab ID numbers)
I've tried the following, and the following without passing wID, since it is an optional parameter
```
chromix raw chrome.tabs.move '{"tabIds":tID, "moveProperties":{"index":-1,"windowId":wID}'
chromix raw chrome.tabs.move [{"tabIds":tID, "moveProperties":{"index":-1,"windowId":wID}]
chromix raw chrome.tabs.move tID, "moveProperties":'{"index":-1,"windowId":wID}'
chromix raw chrome.tabs.move [tID, '{"index":-1,"windowId":wID}']

and a bunch of other variations of this same basic structure but you get the point.
Could someone provide a working example of how this works, or how any raw command with multiple parameters are passed? Thanks in advance


```

**Comment by smblott-github** [comment]
@jackmac79.  Thanks for the report.  It appears there was an unnecessary check on the number of arguments for `raw`.  Fixed here: ca0c65362590e5c483ce4a33ce61853b10621fc9.

This (now) works for me:

    chromix raw chrome.tabs.move 13624 '{"index":-1}'
