### ISSUE TITLE
Project website not available

### ISSUE THREAD

**Issue by episanty** [smblott-github/chromix#12]
The Readme directs users to http://chromix.smblott.org/, but that web page is not available - it returns ERR_NAME_NOT_RESOLVED.

**Comment by smblott-github** [comment]
Thanks for the heads up.
Looks like I goofed up my Apache config, ..., working on it, ...

**Comment by smblott-github** [comment]
(Nah.  It was DNS config error.)  Should be fixed as changes propagate. Thanks, @episanty.
