### ISSUE TITLE
Usage questions, rather than a bug report...

### ISSUE THREAD

**Issue by tinkster** [smblott-github/chromix#14]
How can I get a list of active tabs?

How do I iterate over open tabs if I don't want to use qualifiers?

**Comment by smblott-github** [comment]
`chromix with all list` will give you a list of all tabs.  (I don't think there's a way to get the "active" tab in each window).

To iterate..., I guess you'd need to write a shell script or something.

**Comment by tinkster** [comment]
I went with "or something" and wrote a little python wrapper :}

Cheers
