### ISSUE TITLE
Feature Request: cron job to reload tab every X hours

### ISSUE THREAD

**Issue by matthewlswanson** [smblott-github/chromix#19]
I use chromium-browser to display digital signage on linux. But the browser keeps crashing daily(I'm assuming due to memory running out). I run in incognito mode so I will not be able to use the extension, but I am wondering if with your software there would be a way to make a cron job to reload chrome tabs every so often, or even detect when a tab crashes and reload it then. Any ideas?

Cheers,
Matthew Swanson

**Comment by matthewlswanson** [comment]
I feel like an idiot, I just found out you can enable extension in incognito...

**Comment by smblott-github** [comment]
OK.  It looks like there's not a lot to be done, here.
Closing.
